---

- name: Deactivate any active password policy present in the power HMC
  ibm.power_hmc.hmc_pwdpolicy:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      state: deactivated

- name: Check the password policies present in the power HMC and store it in a variable
  ibm.power_hmc.hmc_pwdpolicy:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      state: facts
      policy_type: policies
  register: policy_check

- name: Create a new password policy in power HMC if the policy name doesn't exist
  ibm.power_hmc.hmc_pwdpolicy:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      policy_name: '{{ password_policy_name }}'
      policy_config: '{{ password_policy_configs }}'
      state: present
  when: policy_check.policy_info | rejectattr('NAME', 'equalto', password_policy_name) | list | count == policy_check.policy_info | length

- name: Modify an existing password policy in power HMC if the policy name already exists
  ibm.power_hmc.hmc_pwdpolicy:
      hmc_host: "{{ inventory_hostname }}"
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      policy_name: '{{ password_policy_name }}'
      policy_config: '{{ password_policy_configs }}'
      state: modified
  when: policy_check.policy_info | selectattr('NAME', 'equalto', password_policy_name) | list | count > 0

- name: Activate the provided created/modified password policy in power HMC
  ibm.power_hmc.hmc_pwdpolicy:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      policy_name: '{{ password_policy_name }}'
      state: activated

- name: Check the list of users present in power HMC and store it in a variable excluding root, hscpe and logged in user
  ibm.power_hmc.hmc_command:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      cmd: lshmcusr -F name | grep -Ev "(root|hscpe|VALUE_SPECIFIED_IN_NO_LOG_PARAMETER\s*)$"
  when: password_policy_password_change is true
  register: userslist

- name: Change password for all the remaining users in power HMC
  ibm.power_hmc.hmc_user:
      state: updated
      hmc_host: "{{ inventory_hostname }}"
      name: '{{ item }}'
      hmc_auth:
          username: "{{ password_policy_hmc_username }}"
          password: "{{ password_policy_hmc_password }}"
      attributes: "{{ password_policy_user_password }}"
  loop: "{{ userslist.command_output }}"
  when: password_policy_password_change is true
