---
- name: Demo HMC update
  hosts: hmcs
  connection: local
  gather_facts: false

  vars:
      curr_hmc_auth:
          username: "{{ ansible_user }}"
          password: "etmZST6Z29BS7!"
      hmc_ip: "{{ inventory_hostname }}"

  tasks:
      - name: Current version
        ibm.power_hmc.vios_update_upgrade:
            hmc_host: '{{ hmc_ip }}'
            hmc_auth: '{{ curr_hmc_auth }}'
            attributes:
                vios_id: 1
                #vios_name: hmc-zz1-vios1
                system_name: hmc-zz1
            state: facts
        register: fact
      
      - name: Output fact
        ansible.builtin.debug:
          msg: "{{ fact }}"

      - name: update vios
        ibm.power_hmc.vios_update_upgrade:
            hmc_host: '{{ hmc_ip }}'
            hmc_auth: '{{ curr_hmc_auth }}'
            attributes:
              repository: sftp
              #vios_name: hmc-zeppelin4-vios1
              vios_id: 1
              system_name: hmc-zz1
              password: Onep@sswd4power
              user_id: hmcct
              host_name: 9.3.115.83
              directory: sreenidhi
              files:
                  - H87538085.iso
            state: updated
        register: output

      - name: Output updated
        ansible.builtin.debug:
          msg: "{{ output }}"