---
- name: Install the VIOS version 3.1.0.10 after copying the image from remote server to Power HMC disk
  hosts: hmcs
  connection: local
  vars:
      curr_hmc_auth:
          username: hscroot
          password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              34656335616165343966323739633761653065346138623233633764353636373063313736373563
              6130373162376464666634363734303164396364656535350a663661636663323434386466383634
              63323432303833643864396130393133346666336661346432356433353035663038643833373332
              3664333762656138640a306539363765343261383363346532643639383938656434333564323139
              6365

  tasks:
      - name: Copy vios installation image of 3.1.0.10 version from sftp location to HMC disk
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: "{{ curr_hmc_auth }}"
            media: sftp
            directory_name: "vios_3.1.0.10"
            remote_server: <sftp_server_ip>
            sftp_auth:
              username: sftp_username
              password: sftp_password
            remote_directory: /home/hmcct/
            files:
               - flash.iso
            action: copy
        register: testout

      - name: Stdout the result of copy
        ansible.builtin.debug:
            msg: '{{ testout }}'

      - name: Install the VIOS using image available in disk for 3.1.0.10 version
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: '{{ curr_hmc_auth }}'
            system_name: <system-name>
            vios_IP: <vios_ip>
            name: <vios-name>
            image_dir: "vios_3.1.0.10"
            vios_iso: dvdimage.v1.iso
            vios_gateway: <gateway_ip>
            vios_subnetmask: <subnetmask_ip>
            network_macaddr: <mac_address>
            action: install
        register: output

      - name: Stdout the result of installation through disk
        ansible.builtin.debug:
            msg: '{{ output }}'
