---
# Secret passwords file

# new password for the users in the power HMC as per the password policy
password_policy_user_password:
    passwd: "Abcde@12345"

# password of the power HMC logged in user
password_policy_hmc_password: Abcde@1234