---
name: run ibm.power_hmc collection unit tests

# run unit test during pull request to dev-collection
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ dev-collection ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']

    name: running unit tests with python ${{ matrix.python-version }}
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install ansible ${{ matrix.ansible-version }}
      run: |
        make install-ansible
        
    - name: install python modules needed for unit testing
      run: |
        make install-unit-test-requirements
        
    - name: run unit tests
      run: |
        make unit-test PYTHON_VERSION=${{ matrix.python-version }}
